### PR TITLE
Fix website for update on 07.2022

### PR DESCRIPTION
**Pull request by nhatthien0812**
https://github.com/verichains/polaris-centre/issues/448

### CODE REVIEW

**Comment by ldt116** [comment]
Preview: https://nhatthien0812.github.io/polarisec.com/home

**Review by ynguyen0610 — DISMISSED** [review]

**Comment by ldt116** [comment]
- [x] Need to change the Gartner logo
- [x] Change to `PCIDSS` -> `PCI-DSS` - in link https://nhatthien0812.github.io/polarisec.com/PCI-DSS
- [x] Fix the menu `PCIDSS` -> `PCI-DSS`
image

**Comment by nhatthien0812** [comment]
> * [x]  Need to change the Gartner logo
> * [x]  Change to `PCIDSS` -> `PCI-DSS` - in link https://nhatthien0812.github.io/polarisec.com/PCI-DSS
> * [x]  Fix the menu `PCIDSS` -> `PCI-DSS`
>   image

Done!

**Comment by ldt116** [comment]
@ynguyen0610 please review again

**Comment by ynguyen0610** [comment]
Edits:

- [x] Delete Cylon and Ice7 logos

image

- Add links 

  - [x] VNG - https://vng.com.vn/
  - [x] Group8 - https://group8.co/
  - [x] Sao Bac Dau - https://saobacdau.vn/
  - [x] VNSec: https://www.vnsecurity.net/


- Add thêm các logo sau:

  - [x] VNG Cloud: https://www.vngcloud.vn
  - [x] E-Cloud Valley: https://www.ecloudvalley.com/
  - [x] NUS: https://www.nus.edu.sg
  - [x] SingTel: https://www.singtel.com

Logo Folder: https://drive.google.com/drive/folders/1pmEtheehvSrRlcGIJo3j0mu4EcJTm0NW

- [x] Email hello chưa highlight (Partners)
image

- [x] Sửa ảnh

image

- [x] Check lại link (Homepage) 
image
"Khi click vào sẽ hiện ra đang ký tài khoản nhưng nội dung là nhận new feature and product updates. 

- [x] Trong phần Pricing, link FAQ tới link này: https://support.polarisec.com/portal/en/kb/polaris-kb/frequently-asked-questions-faq

- [x] Contact sales (Mobile)
image

**Review by ldt116 — APPROVED** [review]

**Pull request merged**
